sudo: required
dist: bionic
language: generic

before_install:
  - sudo apt-get -qq -y install shellcheck
  - sudo apt-get -qq -y install python3-pip
  - sudo pip3 install bashate

script:
- shellcheck setup.sh .ros_shortcut.sh
- bashate setup.sh .ros_shortcut.sh
